/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cm_frame_patch_PatchUtils */

#ifndef _Included_cm_frame_patch_PatchUtils
#define _Included_cm_frame_patch_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef cm_frame_patch_PatchUtils_PATCH_SUCCESS
#define cm_frame_patch_PatchUtils_PATCH_SUCCESS 0L
#undef cm_frame_patch_PatchUtils_PATCH_FAIL
#define cm_frame_patch_PatchUtils_PATCH_FAIL -1L
/*
 * Class:     cm_frame_patch_PatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cm_frame_patch_PatchUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
